-- create database my_name;
-- create table my_name.poser(
-- id int,
-- name varchar(45),
-- age int,
-- primary key(id)
-- );
-- select*from my_name.poser;
--  insert into poser(id,name,age)
--  values ('2','huynh','29');
-- select*from my_name.poser;
-- truncate table poser;
--  select*from my_name.poser;
-- alter table poser
-- add email varchar(45);
-- alter table poser
-- drop column email;
-- truncate table poser;
-- insert into poser(id,name,age)
--  -- values ('2','huynh','29');
-- --  insert into poser(id,name,age)
--   values ('2','huynh','29');
-- alter table poser
-- modify id int;
  select*from my_name.poser;